### ISSUE TITLE
Cobine the differnt fusion results

### ISSUE THREAD

**Issue by KeyTals** [stianlagstad/chimeraviz#1]
Hi Stian,

Is it possible to combine the results of different fusion software in chimraviz then generate just one The fusion report report.

 i.e.  if i ran two fusion software (Ericscript and Fusion catcher), i can import these using the importEricscript() and importFusioncatcher() but i would like to combine these tow objects first then create the html fusion report.

Thanks,
Keyur

**Comment by stianlagstad** [comment]
I'm terribly sorry for my late response - I had turned off email notifications here.

Since the import functions returns lists of Fusion objects, you can combine the lists and create a report from the combined list. Like this:

```
# Import Fusioncatcher fusions
fusioncatcher833ke <- system.file(
  "extdata",
  "fusioncatcher_833ke_final-list-candidate-fusion-genes.txt",
  package = "chimeraviz")
fusioncatcherFusions <- importFusioncatcher(fusioncatcher833ke, "hg38", 3)

# Import Ericscript fusions
ericscriptData <- system.file(
  "extdata",
  "ericscript_SRR1657556.results.total.tsv",
  package = "chimeraviz")
ericscriptFusions <- importEricscript(ericscriptData, "hg19", 3)

# Combine lists
allFusions <- c(fusioncatcherFusions, ericscriptFusions)

# Create report
createFusionReport(allFusions, "test.html")
```

**Comment by stianlagstad** [comment]
Closing this. Let me know if you have any issues :)
