### ISSUE TITLE
object 'alTrackHighlightB' not found

### ISSUE THREAD

**Issue by yboursin** [stianlagstad/chimeraviz#12]
Fetching transcripts for gene partners..
..transcripts fetched.
Selecting transcripts for B3GNT6..
..found transcripts of type intergenic
Selecting transcripts for INCA1..
..found transcripts of type intergenic
As INCA1 is on the minus strand, the plot for this gene will be reversed
Error in Gviz::plotTracks(collapse = FALSE, list(trBtrack, alTrackHighlightB),  :
  object 'alTrackHighlightB' not found
Calls: plotTranscripts -> <Anonymous>

```
Gviz::plotTracks(
        collapse = FALSE, # without this gviz create cluster_X entries in the GeneRegionTrack
        list(grTrackHighlightB, alTrackHighlightB),
        sizes = c(5, 2),
        add = TRUE,
        margin = 3,
        innerMargin = 0,
        # Plot reverse if gene is at minus strand
        reverseStrand = geneBatMinusStrand)
    } else {
      Gviz::plotTracks(
        collapse = FALSE, # without this gviz create cluster_X entries in the GeneRegionTrack
        list(trBtrack, alTrack), <<<<<<<<< here is the stuff
        sizes = c(5, 2),
        add = TRUE,
        margin = 3,
        innerMargin = 0,
        # Plot reverse if gene is at minus strand
        reverseStrand = geneBatMinusStrand)
    }
```

**Comment by stianlagstad** [comment]
Thank you. I just pushed the commits to fix this in the devel branch. Unfortunately the 3.5 branch has been closed due to the 3.6 release happening in a few days, so I was not able to fix it there.
