### ISSUE TITLE
Vignette levels of toc

### ISSUE THREAD

**Issue by llrs** [stianlagstad/chimeraviz#2]
When I visualize the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/chimeraviz/inst/doc/chimeraviz-vignette.html) the section 3.2.1.5 is not shown in the TOC:

You should set the level of depth of the TOC at the yaml header if you want it to be formatted as such
```
---
title: "chimeraviz"
author: "Stian Lågstad"
date: "`r Sys.Date()`"
output: 
  BiocStyle::html_document2:
    toc_depth: 5
vignette: >
  %\VignetteIndexEntry{chimeraviz}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```

**Comment by stianlagstad** [comment]
Thank you for the tip @llrs, but I'll think the TOC looks nice as it is. :)
