### ISSUE TITLE
Coverage not plotted with "plotFusionTranscript"

### ISSUE THREAD

**Issue by JakobHofvander** [stianlagstad/chimeraviz#42]
Thank you for for the nice tool! 
However, I'm not able to get the coverage plotted with the plotFusionTranscipt command, but it works for the other plots. I only get the blue/green exons and the axis.

I'm using bedGraph files and not bam files. I'm using chimeraviz_1.4.3 installed with bioconductor

Also, is it possible to change the axis of only one of the genes in "plotFusion"? I have a very highly expressed 5' partner so if you change the axis its difficult to see the changes in the not so highly expressed 3' partner.

I also have a suggestion for a new plot, not sure if its possible but it would be nice to have something like the "plotTranscripts" but only showing the exons like in "plotFusionTranscipt". Then it would be easier to see if there is a change in coverage at the breakpoint.

/ Jakob

**Comment by plijnzaad** [comment]
Hi, it really depends on what fusion gene caller you are using: it has to provide them, and chimerviz has to support the particular way the tools provides the fusion reads. The example in the vignette uses the deFuse tool (which does supply them). STAR-Fusion (which I am currently working on) also supplies them, but chimeraviz doesn't support it yet (I have something working, I will issue a pull request soon). Cheers,

Ph

**Comment by stianlagstad** [comment]
Hey @JakobHakon, sorry for not answering this. @plijnzaad's answer is correct for your first question. I've recorded your second question as a feature request: https://github.com/stianlagstad/chimeraviz/issues/57. As for the third, please open a new issue if that plot is something that would be useful for you, and I'll add it.
