### ISSUE TITLE
current vignette has lots of warnings

### ISSUE THREAD

**Issue by vjcitn** [stianlagstad/chimeraviz#43]
have a look at

https://bioconductor.org/packages/release/bioc/vignettes/chimeraviz/inst/doc/chimeraviz-vignette.html

there are lots of

## length of NULL cannot be changed

in the document.  Let me know if you need more information.

**Comment by stianlagstad** [comment]
Thank you for bringing this to my attention, @vjcitn! I believe it's caused by https://github.com/tidyverse/readr/issues/750, which now seem to have been fixed. I will look at it shortly.

**Comment by stianlagstad** [comment]
Moving from readr to using data.table in https://github.com/stianlagstad/chimeraviz/commit/bd3f6fd2f7bf40e9fddbfa25fc25bb9384136095

The https://travis-ci.org/stianlagstad/chimeraviz/builds/429227218 build should go green. Will close this PR then.

**Comment by stianlagstad** [comment]
OK for devel. Will do the same changes for release.
