### ISSUE TITLE
Incorrect naming for reads in Ericscript

### ISSUE THREAD

**Issue by matq007** [stianlagstad/chimeraviz#60]
Hi, I was going through your code for importing `ericscript` output and I think you may be naming the counts wrongly.

In the ericscript documentation it is stated:

crossingreads | the number of paired end discordant reads.
-- | --
spanningreads | the number of paired end reads spanning the junction.

In your code, you are defining the variables like this:

```R
# Number of supporting reads
split_reads_count <- report[[i, "crossingreads"]]
spanning_reads_count <- report[[i, "spanningreads"]]
```

Shouldn't it be reversed? I understand it that a discordant read is a form of spanning read when the reads map to two different genes while split read is the read that covers the junction.
Or am I understanding it wrong?
Thank you very much :)

**Comment by stianlagstad** [comment]
I think you are absolutely right!:) Thanks for spotting this! I'll fix it now.

**Comment by stianlagstad** [comment]
Fixed in release 3_8 here: https://github.com/stianlagstad/chimeraviz/commit/c77bbec12f3937d5abe4083a6a7b84121006d55c
Fixed in master here: https://github.com/stianlagstad/chimeraviz/commit/a7fe15007a383ad01480ed2c2e6785c01babfaef

Thanks again!
