### ISSUE TITLE
Question: what are the red bands on the chromosome?

### ISSUE THREAD

**Issue by ahdee** [stianlagstad/chimeraviz#67]
Sorry silly question but what are the red bands on the chromosome shown here, 
![cF443qJ 1](https://user-images.githubusercontent.com/9808122/57048038-670de900-6c27-11e9-8bfe-bd6cffee9c20.png)

**Comment by stianlagstad** [comment]
That's  a very good question! And I really don't know. chimeraviz use these files with cytoband information:
1. https://github.com/stianlagstad/chimeraviz/blob/master/inst/extdata/UCSC.HG19.Human.CytoBandIdeogram.txt, downloaded from http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/
2. https://github.com/stianlagstad/chimeraviz/blob/master/inst/extdata/UCSC.HG38.Human.CytoBandIdeogram.txt, downloaded from http://hgdownload.cse.ucsc.edu/goldenpath/hg38database/
3. https://github.com/stianlagstad/chimeraviz/blob/master/inst/extdata/UCSC.MM10.Mus.musculus.CytoBandIdeogram.txt, downloaded from http://hgdownload.cse.ucsc.edu/goldenPath/mm10/database/

This data is sent to the [Gviz package](http://bioconductor.org/packages/release/bioc/html/Gviz.html), which chimeraviz uses for most visualizations. If you look at the [manual for gviz](http://bioconductor.org/packages/release/bioc/manuals/Gviz/man/Gviz.pdf) and search for "IdeogramTrack class and method", you can see that the description of "bands" parameter (which chimeraviz use to input the files from above) is this:
> A data.frame with the cytoband information for all available chromosomes on the genome similar to the data that would be fetched from UCSC. The table needs to contain the mandatory columns chrom, chromStart, chromEnd, name and gieStain with the chromosome name, cytoband start and end coordinates, cytoband name and coloring information, respectively.

I googled various terms related to "gieStain" and found these links interesting:
- https://en.wikipedia.org/wiki/Giemsa_stain
- https://www.researchgate.net/post/About_Giemsa_stain_What_is_the_target_of_Giemsa_in_chromosomes
- https://www.nature.com/scitable/topicpage/karyotyping-for-chromosomal-abnormalities-298
- http://www.cellmarque.com/cmsial-literature/304-Giemsa-Academia.pdf

But I still don't know why the colors are what they are, nor what the different colors mean. Do post back if you figure anything out :)

**Comment by ahdee** [comment]
Thanks! that file you sent was super helpful.  I think its the "stalk" because searching through each one there are only a few chromosome that has it ( Acrocentric chromosomes)  and they are according to this cite on the short arm.  I've tested on random example with the chr that has the stalk and as you can see it seems to match. 
![3izEFFn 1](https://user-images.githubusercontent.com/9808122/57249705-7fe91680-6ffa-11e9-8ad4-417bea439239.png)

cite: https://diagnosticcytogenetics.com/about/glossary/

**Comment by stianlagstad** [comment]
I'm glad the file was helpful. I'll assume the question is answered then and close this issue.

**Comment by ahdee** [comment]
@stianlagstad thanks again!
