### ISSUE TITLE
coverage issue in plot_fusion_separate

### ISSUE THREAD

**Issue by DanieleDallOlio** [stianlagstad/chimeraviz#75]
Hi there,
I am trying to use plot_fusion but I am not able to produce the plot with coverage data (I do not get an Error, I just do not get the coverage subplot). I looked into your code and I think I found an explanation at lines 617, 679, 743 in plot_fusion.R and they all involve ' exists("al_track") ' . 
Is not supposed to be ' exists("alignment_track") ' instead of ' exists("al_track") ' ?

It makes sense in plot_fusion_together since you define 'al_track', but it does not in plot_fusion_separate because you define 'alignment_track' .

Please let me know what you think, thank you!!

**Comment by stianlagstad** [comment]
Thank you @DanieleDallOlio ! :)

I've made the required changes in the devel version 1.13.3 (commit https://github.com/stianlagstad/chimeraviz/commit/149bf55d27cf3234a99cebe771c24f08ab88e5d6), and the release version 1.12.3 (commit https://github.com/stianlagstad/chimeraviz/commit/18940b3370c84951e069a1be5b980522cc55d120).

Please let me know if this solves the issue on your end.

**Comment by DanieleDallOlio** [comment]
Yes, it works now.
Thanks a lot !!
