### ISSUE TITLE
How to make fusioncatcher data compatible to chimeraviz

### ISSUE THREAD

**Issue by cetienn01** [stianlagstad/chimeraviz#82]
Hello,

I am trying to visualize GeneFusion data from FusionCatcher, however, it seems that my data is in a different format from what the Chemiaviz package use. I looked at the sample data included with the turtorial and it is different.
Is there some preliminary steps involved to make the data compatible, to make it look the same as the data in the turorial.

Thank you for your interest in chimeraviz. To make it easier for me to help you, please provide this information in your submitted issue:

Here's what my data looks like..
![Screen Shot 2020-04-15 at 1 27 29 PM](https://user-images.githubusercontent.com/46975293/79368184-fe457c80-7f1c-11ea-9638-b9cd50c22f33.png)
See below for details about the software version and OS version i am using for analysis

1. The output of `sessionInfo()`.
**N/A**
2. Which fusion-finder tool you are using, and its version.
**Software version: fusioncatcher.py 1.00**
3. Which operating system you are using, and its version.
**MacOS Catalina
Version 10.15.3**

4. Example code leading to the error (if you're experiencing an error).
**N/A**

**Comment by cetienn01** [comment]
Actually, from looking at the data that is available with the Chimeraviz package, i realized that my gene fusion data from FusionCatcher was already in the same format. So i did a bulk import of all the GeneFusions data. I will close this issue now.

**Comment by stianlagstad** [comment]
Hi @cetienn01 ! Do let me know if you have any further issues :)

**Comment by cetienn01** [comment]
Thank you @stianlagstad .
Another thing i've noticed is that, it's not quite straightforward how to modify the gene fusions plot using the `plot_circle(fusions)` function. I can see that this function is using the **RCircos package**, which has many more features, but the plot function only takes one argument (the fusion_list). Maybe I'll open a new issue to discuss this question and see how to access/change Rcircos parameters within the Chimeraviz package (without having to play with the source code too much).

**Comment by stianlagstad** [comment]
Good idea! Please do open another issue if you have anything specific in the underlying libraries that you wish you'd be able to control through chimeraviz.
