### ISSUE TITLE
plot_fusion_transcript_with_protein_domain():  error plotting upstream domains

### ISSUE THREAD

**Issue by ivanbelzen** [stianlagstad/chimeraviz#87]
Hi! 

Thanks for the convenient package to visualize gene fusions!
I've come across an error whilst trying to visualize protein domains. The downstream gene seems to work fine but for the upstream gene only lines with start coordinates as label are displayed instead of proper protein domain blocks. 

Looking at the code of plot_fusion_transcript_with_protein_domain.R  it is quite easily seen where the bug is, if you compare upstream/downstream gene code, because start coordinates are used instead of end coordinates and instead of the description label. (lines 778 and 788)

Could you fix this?

Best regards,
Ianthe van Belzen

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin18.7.0 (64-bit)
Running under: macOS Mojave 10.14.6
chimeraviz_1.16.0

**Comment by stianlagstad** [comment]
Thanks @ivanbelzen ! Like this? https://github.com/stianlagstad/chimeraviz/pull/88

**Comment by stianlagstad** [comment]
Thanks again. The change will be available in v1.16.1 in release_12, and v1.17.1 in devel.
