### ISSUE TITLE
Fusion transcript plot with protein domain annotations

### ISSUE THREAD

**Issue by JReneWong** [stianlagstad/chimeraviz#99]
Hello, 

My question is about interpretation of this plot. What does the change in the thickness of the fusion represent? Are these the 5' - 3' UTRs? 

Thank you very much! 

![Screenshot 2024-02-02 at 4 37 28 PM](https://github.com/stianlagstad/chimeraviz/assets/109715527/69d8f181-58dc-4a69-a734-1ea58df3bd67)

**Comment by stianlagstad** [comment]
Hi @JReneWong , thanks for the question. I believe the difference between the thickness is that the thinner ones are noncoding regions, while the thicker ones are coding regions. You can read more about it in the manual for gviz here: https://bioconductor.org/packages/devel/bioc/vignettes/Gviz/inst/doc/Gviz.html
